#!/usr/bin/env bash

set -e

# Remove any previously compiled versions.
rm *.vsix || true

echo "================================================================================"
echo "Packaging extension..."
echo "================================================================================"
yes | vsce package

# Install the compiled extension.
echo ""
echo "================================================================================"
echo "Installing extension..."
echo "================================================================================"

# Uninstalling the old version seems to be necessary to force Code to pick up the new version reliably.
code --uninstall-extension phillco.cursorless-sidecar || true
code --install-extension *.vsix --force

if [[ -x "$(command -v code-insiders)" ]]; then
  # Also install into insiders, if it exists.
  code-insiders --uninstall-extension phillco.cursorless-sidecar || true
  code-insiders --install-extension *.vsix --force
fi

echo ""
echo "================================================================================"
echo "Reloading VS Code..."
echo "================================================================================"

# Use the command socket to tell VS Code to reload in the background, if socat is installed.
if [[ $(type -P "socat") ]] && [[ -e ~/.cursorless/vscode-socket ]]; then
  echo "Reloading VS Code using the command socket..."
  echo '{ "command": "command", "commandId": "workbench.action.reloadWindow" }' | socat - ~/.cursorless/vscode-socket
else
  echo "Not automatically reloading VS Code because \`socat\` is not installed"
  echo "Reload the VS Code window manually (\"window reload\") to get the new version"
fi

echo "Done"
